// <auto-generated />
namespace WebAPP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Entidadcreatetable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Entidadcreatetable));
        
        string IMigrationMetadata.Id
        {
            get { return "202506111801581_Entidad-create-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
